title: Imam
email: i.mail@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
  I’m all about turning raw data into clear, visual stories. From digging into datasets to uncover insights, to building models and dashboards that make data come alive—I thrive where analysis meets creativity.

# into data analytics, data modeling, and software dev. I love
# diving into datasets to find cool insights, building data models for
# efficiency, and creating software that solves problems and drives
# innovation.

# # -- activate when in dev mode
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# # -- activate when in prod mode
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://immsswd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# social-media
twitter_username: null
github_username: null

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 7 # Number of posts per page
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title/

# code highlighter
markdown: kramdown
highlighter: rouge
input: GFM
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
