title: IMM
favicon: /assets/favi.png
description: I'm into data analytics, data modeling, and software dev. I love diving into datasets to find cool insights, building data models for efficiency, and creating software that solves problems and drives innovation.
# logo: /assets/img/logo.png
# show_downloads: true

theme: jekyll-theme-minimal
# Pagination settings
plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page:num/"
