title: IMM
# logo: /assets/img/logo.png
# favicon: /assets/img/favicon.png

description: This is a portfolio of data analyst projects.

show_downloads: true

theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Custom styles
style: /style.scss
